### ISSUE TITLE
Question about the network size

### ISSUE THREAD

**Issue by persistz** [mlech26l/qnn_robustness_benchmarks#1]
Hi @mlech26l,

In readme file you mentioned that the network size should be `784-64-32-10`.

But in the `check_mnist_robustness` file, why the model is defined by:`QuantizedModel([64, 32], ...`.
Where is the 10 dim output layer?

George

**Comment by mlech26l** [comment]
Hi @persistz 

Yes, that seems to be a bug. Thanks for noticing.

So the network is actually 784-64-32 with the output layer having 32 units but only the first 10 are used for the classification.

**Comment by persistz** [comment]
Hi @mlech26l 

Thanks, I got it. 
I will use the first 10 output nodes as the output layer, hope the max value will not appear in other nodes.
I notice that you have modified the readme file, so I close this issue. 😊😊
