### ISSUE TITLE
About quantization_config

### ISSUE THREAD

**Issue by zhangyedi** [mlech26l/qnn_robustness_benchmarks#2]
Hi, @mlech26l 

When I read your code, I'm confused about the reason why you set "quantization_config" in your "QuantizedModel" class as follows,
            "int_bits_weights": 1,  # Signed, +-0.3
            "int_bits_bias": 2,  # Signed, +-1.2
            "int_bits_activation": 2,  # Unsigned (relu), +1.3
            "int_bits_input": 0,  # Unsigned (relu), +1.3"? 

1. Does it have anything to do with the way you trained the benchmark? Or, it is only designed for computing the minimal amount of bits more conveniently? :)
2. And what does the comment mean? like, +-0.3, +-1.2, +1.3

Yedi

**Comment by mlech26l** [comment]
HI @zhangyedi 

The ```quantization_config``` dict allows you to configure the fixed-point format that is used for the quantization.
For the 6-bit networks used in the paper, 
```int_bits_weights=1``` defines the number of integer bits, i.e., 1 bit for the sign, 1 bit for the integer part, and 4 bits for the fractional part. 

Activation and inputs have no sign bit.

The values in the dict are the ones the provided networks are trained with.

The comments are outdated and only for debugging.

**Comment by zhangyedi** [comment]
Thanks~! And, can you tell me the accuracy of the benchmark you used here 784-64-10 with the 6-bit network as well as the predefined quantization_config (If you trained it in a fixed-point way). Or else, if the network is trained in a floating-point way, then what is the activation function you used in it? Is it just Relu or ReLu-N? I guess it is ReLu-N with N<=3 (2**2-1) because I notice you preserve 2 bits for the integer part of the activation value. :)

**Comment by mlech26l** [comment]
The networks were trained with quantization-aware training with the predefined fixed-point scheme given in your first post.

The activation function is defined as
```python
def fake_quant_op_activation(x, quantization_config, signed_output):
    num_bits = quantization_config["quantization_bits"]
    frac_bits = num_bits - quantization_config["int_bits_activation"]
    if signed_output:
        min_val, max_val = int_get_min_max(num_bits, frac_bits)
    else:
        min_val, max_val = uint_get_min_max(num_bits, frac_bits)
    return tf.quantization.fake_quant_with_min_max_args(
        x, min=min_val, max=max_val, num_bits=num_bits
    )
```
, i.e., for the hidden layers a ReLU-N (with low=0 and high=maximum representable number by the fixed-point scheme).

Test accuracy of the MNIST network is 97.08% and for the Fashion-MNIST model, it is 85.60%.
